# Note: This example is for the alpha feature of server side apply.
# It requires the provider to be started with the --enable-server-side-apply flag.
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: sample-service-owner
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Service
      metadata:
        name: sample-service
        namespace: default
        labels:
          example: "true"
      spec:
        selector:
          app.kubernetes.io/name: MyApp
        ports:
          - protocol: TCP
            port: 80
            targetPort: 9376
  providerConfigRef:
    name: kubernetes-provider
---
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: sample-service-labeler
spec:
  # Note: This resource will only patch/update the manifest below.
  # It will not delete or create the resource.
  # As a limitation, it will not clean up the changes it made during its deletion.
  managementPolicies: ["Observe", "Update"]
  forProvider:
    manifest:
      apiVersion: v1
      kind: Service
      metadata:
        name: sample-service
        namespace: default
        labels:
          another: label
  providerConfigRef:
    name: kubernetes-provider