apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: sample-namespace
  annotations:
    uptest.upbound.io/timeout: "60"
    # Note(turkenh): Import restarts Crossplane pod losing the cached provider package
    # hence preventing changes being redeployed with modified deployment runtime config.
    uptest.upbound.io/disable-import: "true"
spec:
  # Watch for changes to the Namespace object.
  # Watching resources is an alpha feature and needs to be enabled with --enable-watches
  # in the provider to get this configuration working.
  # watch: true
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        # name in manifest is optional and defaults to Object name
        # name: some-other-name
        labels:
          example: "true"
  providerConfigRef:
    name: kubernetes-provider
